version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:./prometheus.yml
    command:
      - '--config.file=./prometheus.yml'
      - '--storage.tsdb.retention.time=15d'
      - '--web.enable-lifecycle'

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=parmesh
      - GF_SECURITY_ADMIN_PASSWORD=P27m_09@b0
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
